[phases.setup]
nixPkgs = ["chromium", "glib", "nss", "freetype", "fontconfig", "alsa-lib", "atk", "cups", "dbus", "expat", "libdrm", "libX11", "libxcb", "libxkbcommon", "mesa", "nspr", "pango", "systemd", "libXrandr", "libXcomposite", "libXdamage", "libXext", "libXfixes"]

[phases.install]
cmds = ["npm install"]
